checks:
  - CheckCrossSiteScripting
  - CheckBrokenAuthCheck
  - CheckDirectoryTraversalCallAlerts
  - CheckDirectoryTraversalCRstrbReadBuffered
  - CheckDirectoryTraversalReadDataset
  - CheckDirectoryTraversalRfcRemoteFile
  - CheckDirectoryTraversalDeleteDataset
  - CheckDosInDoLoop
  - CheckExposedSystemCalls
  - CheckOSCommandInjectionCallSystem
  - CheckOSCommandInjectionCFunction
  - CheckHardcodedCredentials
  - CheckOSCommandInjectionClientOS
  - CheckDummyAuthCheck
  - CheckOSCommandInjectionOpenDatasetFilter
  - CheckOSCommandInjectionRfcRemoteExec
  - CheckOSCommandInjectionRfcRemotePipe
  - CheckHardcodedUrls
  - CheckOSCommandInjectionSxpg
  - CheckDangerousAbapCommands
  - CheckAbapOutgoingFtpConn
  - CheckWeakHashingAlgorithms
  - CheckHardcodedIpAddresses
  - CheckHardcodedUserAuth
  - CheckDeleteDynpro
  - CheckCallTransformation
  - CheckGetPersistentByQuery
  - CheckExecuteProcedure
  - CheckGenerateSubroutinePool
  - CheckDirectoryTraversalTransfer
  - CheckHardcodedITIN



file_extensions:
  - .txt
  - .DECOMP

exclude_patterns:
  - "**/test/**"